# Generated by Django 3.2.3 on 2021-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('users', '0002_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='permissions.CustomPermission'),
        ),
    ]
