# Generated by Django 3.2.3 on 2021-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'user_permission',
                'verbose_name_plural': 'users_permissions',
                'db_table': 'permission_custom',
                'ordering': ('name',),
            },
        ),
    ]
